# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon = false

# Mod Properties
mod_version = 0.2.15-beta
maven_group = me.cortex
archives_base_name = voxy
mod_name = Voxy

jedisVersion=5.1.0
rocksdbVersion=10.2.1
commonsPoolVersion=2.12.0
lz4Version=1.8.0
xzVersion=1.10
sqliteJdbcVersion=3.49.1.0
useRubyOnly=true

fabric_loader_version=0.19.5