# Version-specific properties for 1.21.1 Fabric
deps.minecraft=1.21.1
# optional: loader hint for this node
stonecutter.loader=fabric
# Library versions
lwjglVersion=3.3.3
fabric_api_version=0.116.12+1.21.1

# Fabric-specific dependency versions
deps.sodium=0.8.13+mc1.21.1
deps.sodium.modrinth=false
deps.lithium=mc1.21.1-0.15.0-fabric
deps.nvidium_maven=drouarb
deps.nvidium=0.4.1-beta9:1.21-1.21.1@jar
deps.modmenu=11.0.3
deps.iris=1.8.8+1.21.1-fabric
deps.sodium.extra=mc1.21.1-0.6.0+fabric
deps.chunky=1.4.23-fabric
deps.spark=1.10.152-fabric
deps.fabric.permissions=0.3.3
deps.vivecraft=1.21.9-1.3.2-fabric
deps.flashback=rNCr1Rbs